[package]
name = "battery_measurement"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acpi = "4.1.1"
battery = "0.7.8"
chrono = "0.4.26"
home = "0.5.5"
